version: 2
updates:
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "daily" # "weekly", "monthly"
      open-pull-requests-limit: 5
      allow:
          - dependency-type: "direct"
