name: Add contributors
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    schedule:
        - cron: "20 20 * * *"

jobs:
    add-contributors:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write # cần quyền này để tạo PR
        steps:
            - uses: actions/checkout@v2

            - uses: BobAnkh/add-contributors@master
              with:
                  CONTRIBUTOR: "## ✨ Contributors"
                  COLUMN_PER_ROW: "6"
                  ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  IMG_WIDTH: "80"
                  FONT_SIZE: "12"
                  PATH: "/README.md"
                  COMMIT_MESSAGE: "docs(README): update contributors"
                  AVATAR_SHAPE: "round"

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v6
              with:
                  commit-message: "docs(README): update contributors"
                  title: "docs: update contributors"
                  body: "Automated update of contributors list"
                  branch: "bot/update-contributors"
