name: Add contributors

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    schedule:
        - cron: "20 20 * * *" # chạy hàng ngày lúc 20:20 UTC

jobs:
    add-contributors:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Add contributors to README
              uses: BobAnkh/add-contributors@master
              with:
                  CONTRIBUTOR: "## ✨ Contributors"
                  COLUMN_PER_ROW: "6"
                  ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  IMG_WIDTH: "80"
                  FONT_SIZE: "12"
                  PATH: "/README.md"
                  COMMIT_MESSAGE: "docs(README): update contributors"
                  AVATAR_SHAPE: "round"

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v6
              with:
                  commit-message: "docs(README): update contributors"
                  title: "docs: update contributors"
                  body: "This pull request was automatically generated by a GitHub Action to update the list of contributors in the README."
                  branch: "bot/update-contributors"
                  delete-branch: true
