name: Python Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12"]

        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install uv
              run: |
                  curl -LsSf https://astral.sh/uv/install.sh | sh
                  echo "$HOME/.cargo/bin" >> $GITHUB_PATH

            - name: Install dependencies using uv
              run: uv pip install -r <(uv pip compile pyproject.toml --all-extras) && uv pip install ".[dev]"

            - name: Run tests with pytest
              run: uv run pytest
